kafka:
  topic:
    product: Kafka-tutorial-topic       # TODO: Change topic
  consumer:
    bootstrap-servers: 127.0.0.1:100001 # TODO: Change bootstrap server
    group-id: kafka-tutorial-group      # TODO: Change group-id
